CREATE TABLE [notification].[Email]
(
	[Id]		UNIQUEIDENTIFIER	NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Name]		NVARCHAR(100)		NOT NULL,
	[Sender]	NVARCHAR(100)		NOT NULL,
	[Body]		NVARCHAR(1000)		NOT NULL,
	[SentDate]	DATETIME			NULL,
	[CreatedAt]	DATETIME			NOT NULL DEFAULT GETDATE()
)
