/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */

export interface AboutMe {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  greeting?: string | null;
  /** @nullable */
  description?: string[] | null;
}
