/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */

export interface Business {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  taxNumber?: string | null;
  /** @nullable */
  registrationNumber?: string | null;
  /** @nullable */
  street?: string | null;
  /** @nullable */
  postalCode?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  region?: string | null;
}
