/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */

export interface Certificate {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  issuer?: string | null;
  issuedOn?: string;
  /** @nullable */
  code?: string | null;
}
