/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */
import type { Language } from './language';
import type { Hero } from './hero';
import type { SkillCategory } from './skillCategory';
import type { Project } from './project';
import type { Experience } from './experience';
import type { Education } from './education';
import type { Fact } from './fact';
import type { Contact } from './contact';

export interface ContentResponse {
  language?: Language;
  hero?: Hero;
  /** @nullable */
  skillsCategories?: SkillCategory[] | null;
  /** @nullable */
  projects?: Project[] | null;
  /** @nullable */
  experiences?: Experience[] | null;
  /** @nullable */
  educations?: Education[] | null;
  /** @nullable */
  facts?: Fact[] | null;
  /** @nullable */
  contacts?: Contact[] | null;
}
