/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */

export interface Contact {
  /** @nullable */
  type?: string | null
  /** @nullable */
  value?: string | null
  isExternal?: boolean
}
