/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */

export interface EducationDto {
  /** @nullable */
  degree?: string | null;
  /** @nullable */
  field?: string | null;
  /** @nullable */
  institution?: string | null;
  startDate?: string;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  description?: string | null;
}
