/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */

export interface Education {
  /** @nullable */
  institution?: string | null;
  /** @nullable */
  degree?: string | null;
  /** @nullable */
  field?: string | null;
  startDate?: string;
  /** @nullable */
  endDate?: string | null;
}
