/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */

export interface ExperienceDto {
  /** @nullable */
  position?: string | null;
  /** @nullable */
  company?: string | null;
  startDate?: string;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  achivements?: string[] | null;
  /** @nullable */
  technologies?: string[] | null;
}
