/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */
import type { ExperienceArea } from './experienceArea';
import type { Technology } from './technology';

export interface Experience {
  /** @nullable */
  employer?: string | null;
  /** @nullable */
  position?: string | null;
  startDate?: string;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  areas?: ExperienceArea[] | null;
  /** @nullable */
  technologies?: Technology[] | null;
}
