/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */
import type { AboutMeDto } from './aboutMeDto';

export interface HeroDto {
  /** @nullable */
  motto?: string | null;
  aboutMe?: AboutMeDto;
}
