/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */
import type { AboutMe } from './aboutMe';

export interface Hero {
  /** @nullable */
  motto?: string | null;
  aboutMe?: AboutMe;
}
