/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */

export interface NotificationRequest {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  sender?: string | null;
  /** @nullable */
  message?: string | null;
}
