/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */
import type { Technology } from './technology';

export interface Project {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  goal?: string | null;
  /** @nullable */
  solution?: string | null;
  /** @nullable */
  codeUrl?: string | null;
  /** @nullable */
  technologies?: Technology[] | null;
}
