/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */
import type { Technology } from './technology';
import type { ProjectArchitectureNote } from './projectArchitectureNote';
import type { ProjectArchitectureBlock } from './projectArchitectureBlock';

export interface Project {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  goal?: string | null;
  /** @nullable */
  solution?: string | null;
  /** @nullable */
  codeUrl?: string | null;
  /** @nullable */
  technologies?: Technology[] | null;
  /** @nullable */
  architectureNotes?: ProjectArchitectureNote[] | null;
  /** @nullable */
  architectureBlocks?: ProjectArchitectureBlock[] | null;
  /** @nullable */
  architectureCaption?: string | null;
  /** @nullable */
  architectureDiagramLabel?: string | null;
}
