/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */

export interface ProjectDto {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  technologies?: string[] | null;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  codeUrl?: string | null;
  /** @nullable */
  liveUrl?: string | null;
}
