/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */

export interface ProjectArchitectureBlock {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  note?: string | null;
  /** @nullable */
  url?: string | null;
  /** @nullable */
  linkLabel?: string | null;
  /** @nullable */
  connectionLabel?: string | null;
  /** @nullable */
  children?: ProjectArchitectureBlock[] | null;
}
