/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */

export interface Service {
  /** @nullable */
  iconSlug?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
}
