/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */
import type { SkillDto } from './skillDto';

export interface SkillCategoryDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  skills?: SkillDto[] | null;
}
