/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */
import type { Skill } from './skill';

export interface SkillCategory {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  skills?: Skill[] | null;
}
