/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */
import type { Technology } from './technology';

export interface Specialization {
  /** @nullable */
  tag?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  subtitle?: string | null;
  /** @nullable */
  technologies?: Technology[] | null;
}
