/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */

export interface Technology {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  iconSource?: string | null;
  /** @nullable */
  iconSlug?: string | null;
  /** @nullable */
  iconIsMonochrome?: boolean | null;
}
