<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\Portfolio.BuildingBlocks.Application\Portfolio.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\Portfolio.Content.Contracts\Portfolio.Content.Contracts.csproj" />
    <ProjectReference Include="..\Portfolio.Content.Domain\Portfolio.Content.Domain.csproj" />
  </ItemGroup>

</Project>
