CREATE TABLE [content].[AboutMe]
(
	[Id]		UNIQUEIDENTIFIER	NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[HeroId]	UNIQUEIDENTIFIER	NOT NULL,
	[Title]		NVARCHAR(500)		NOT NULL,
	[Header]	NVARCHAR(500)		NULL,

	CONSTRAINT [FK_AboutMe_Hero] FOREIGN KEY ([HeroId]) REFERENCES [content].[Hero] ([Id])
)
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_AboutMe_HeroId] ON [content].[AboutMe] ([HeroId])
