CREATE TABLE [content].[SkillCategory]
(
	[Id]		UNIQUEIDENTIFIER	NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[PL]		NVARCHAR(200)		NOT NULL,
	[EN]		NVARCHAR(200)		NOT NULL,
	[Order]		INT					NOT NULL DEFAULT 0
)
