name: portfolio-${ENV_NAME:-dev}

services:
  db-migrator:
    image: ghcr.io/wiktorwijata/portfolio-db-migrator:${MIGRATOR_TAG:-dev-latest}
    container_name: portfolio-db-migrator-${ENV_NAME:-dev}
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./config/migrator.appsettings.Production.json:/app/appsettings.Production.json:ro
    networks:
      - proxy
    restart: "no"

  api:
    image: ghcr.io/wiktorwijata/portfolio-api:${API_TAG:-dev-latest}
    container_name: portfolio-api-${ENV_NAME:-dev}
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./config/api.appsettings.Production.json:/app/appsettings.Production.json:ro
    networks:
      - proxy
    depends_on:
      db-migrator:
        condition: service_completed_successfully

  web:
    image: ghcr.io/wiktorwijata/portfolio-web:${WEB_TAG:-dev-latest}
    container_name: portfolio-web-${ENV_NAME:-dev}
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    networks:
      - proxy

networks:
  proxy:
    name: ${PROXY_NETWORK:-proxy}
    external: true
