/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Portfolio.Api
 * OpenAPI spec version: 1.0
 */

export interface ContactDto {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  value?: string | null;
  /** @nullable */
  title?: string | null;
  isExternal?: boolean;
}
