export const PROJECTS_GRID_CONFIG = {
  VISIBLE_COUNT: 3,
  COLLAPSIBLE_MAX_HEIGHT: '3000px',
  COLLAPSIBLE_MIN_HEIGHT: '530px',
  COLLAPSIBLE_DURATION: 0.7,
  ANIMATION_STAGGER_DELAY: 0.1,
  ANIMATION_DURATION: 0.4
};
